services:
  app:
    build: 
      context: .
      dockerfile: Containerfile

    userns_mode: ${PODMAN_USERNS:-host}
    
    security_opt:
      - "label=disable"
      - seccomp:unconfined

    cap_add:
      - SYS_PTRACE
      
    init: true

    volumes:
      - ./:/workspace:cached,Z
      
    command: sleep infinity